// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELaXnpJs6rFGd8yTfhM52M7548pFnVvs',
    appId: '1:556540308936:web:7c82396eb903f673d6a4fd',
    messagingSenderId: '556540308936',
    projectId: 'notificacionespush-8207b',
    authDomain: 'notificacionespush-8207b.firebaseapp.com',
    storageBucket: 'notificacionespush-8207b.firebasestorage.app',
    measurementId: 'G-JTFQJMSMDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaph5KZA1negPqrW7nN97EPeBnq1NkpI8',
    appId: '1:556540308936:android:eba1e392b165d30cd6a4fd',
    messagingSenderId: '556540308936',
    projectId: 'notificacionespush-8207b',
    storageBucket: 'notificacionespush-8207b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrprD-W2lMcWxS4Hq5giqhqoo3UYo0EbU',
    appId: '1:556540308936:ios:1884a337811948e4d6a4fd',
    messagingSenderId: '556540308936',
    projectId: 'notificacionespush-8207b',
    storageBucket: 'notificacionespush-8207b.firebasestorage.app',
    iosBundleId: 'com.example.notificacionesPush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrprD-W2lMcWxS4Hq5giqhqoo3UYo0EbU',
    appId: '1:556540308936:ios:1884a337811948e4d6a4fd',
    messagingSenderId: '556540308936',
    projectId: 'notificacionespush-8207b',
    storageBucket: 'notificacionespush-8207b.firebasestorage.app',
    iosBundleId: 'com.example.notificacionesPush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBELaXnpJs6rFGd8yTfhM52M7548pFnVvs',
    appId: '1:556540308936:web:45571077b3bf877bd6a4fd',
    messagingSenderId: '556540308936',
    projectId: 'notificacionespush-8207b',
    authDomain: 'notificacionespush-8207b.firebaseapp.com',
    storageBucket: 'notificacionespush-8207b.firebasestorage.app',
    measurementId: 'G-XFRD91Y1QN',
  );
}
